spring.application.name=splitnings

spring.config.import=optional:file:.env

server.port=8000
# server.servlet.contextPath=/api

# --- OPENAPI ---
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logger
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.root=INFO
logging.level.com.feis.splitnings=INFO

# --- LOGGING ---
logging.file.path=logs
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.file-name-pattern=logs-%d{yyyy-MM-dd}.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - [%thread] %logger{36} - %msg%n

spring.output.ansi.enabled=DETECT

# --- DATABASE ---
spring.datasource.url=jdbc:h2:mem:splitnings
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_audit
spring.jpa.properties.org.hibernate.envers.revision_field_name=revision_id
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revision_type
spring.jpa.properties.hibernate.integration.envers.enabled=false

# --- OAUTH ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/splitnings

splitnings.security.keycloak.server-url=${KEYCLOAK_SERVER_URL}
splitnings.security.keycloak.realm=${KEYCLOAK_REALM}
splitnings.security.keycloak.username=${KEYCLOAK_USERNAME}
splitnings.security.keycloak.password=${KEYCLOAK_PASSWORD}
splitnings.security.keycloak.client-id=${KEYCLOAK_CLIENT_ID}

splitnings.keycloak.realm-name=splitnings

